project:
  type: website
  output-dir: docs

website:
  page-footer:
    center:
      - text: "About"
        href: about.qmd
      #- text: "Feedback"
     #   href: #
      #- text: "Coffee"
       # href: #
  title: "GoData.ca"
  site-url: Godata.ca
  #description: "GoData Blog"
  navbar:
    logo: "avatar-chien01-clipart-md.png"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/murphy99
      #- icon: bluesky
      #  href: https://bsky.app/profile/godata.bsky.social
      - icon: huggingface
        href: https://godata-fables-beta.hf.space/
      - icon: rss
        href: index.xml
    
format:
  html:
    theme: flatly
    footer: dark
    css: styles.css
    include-in-header: gtm_code_head.html
    #include-before-body: gtm_code_body.html
    #include-after-body: Comments.html
    comments:
      utterances:
         repo: "murphy99/murphy99.github.io"
         


    
#filters:
  #- shinylive

editor: visual


